import { PrismaClient, Report } from '@prisma/client';
import nodemailer from 'nodemailer';
import { GoogleGenerativeAI } from "@google/generative-ai";
import dotenv from 'dotenv';

dotenv.config();

const prisma = new PrismaClient();
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || '');

// Create reusable transporter object using the default SMTP transport
const transporter = nodemailer.createTransport({
    host: process.env.SMTP_HOST || 'smtp.gmail.com',
    port: parseInt(process.env.SMTP_PORT || '587'),
    secure: false, // true for 465, false for other ports
    auth: {
        user: process.env.SMTP_USER, 
        pass: process.env.SMTP_PASS, 
    },
});

export const triggerCitizenAdvocate = async (reportId: string): Promise<void> => {
    console.log(`🤖 [Agent 1] Citizen Advocate Agent triggered for Report ${reportId}`);

    try {
        const report = await prisma.report.findUnique({
            where: { id: reportId },
            include: { user: true, images: true }
        });

        if (!report) throw new Error("Report not found");

        const authorityEmail = process.env.AUTHORITY_CONTACT_EMAIL || "test-authority@example.com";
        
        // 1. Generate Formal Complaint using Gemini
        const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash" });
        const prompt = `
            You are the "Citizen Advocate AI", an autonomous agent acting on behalf of a citizen.
            Write a formal, polite, but urgent complaint email to a municipal authority indicating an infrastructure issue.
            
            Details:
            - Tracking ID: ${report.trackingId}
            - Issue Category: ${report.category}
            - User Description: ${report.description || 'No description provided.'}
            - AI Analyzed Severity: ${report.severity}
            - Coordinates: Lat ${report.lat}, Lng ${report.lng}

            Draft ONLY the body of the email. Do not include subject line or placeholders requiring edits. Make it sound professional and ready to send.
        `;

        let emailBody = "An infrastructure issue has been reported. (AI generation skipped or failed).";
        if (process.env.GEMINI_API_KEY) {
            const result = await model.generateContent(prompt);
            emailBody = result.response.text();
        }

        const primaryImage = report.images.find(img => img.isPrimary)?.imageUrl || report.images[0]?.imageUrl || "";

        // Send the email (Mocked if SMTP missing or using real SMTP)
        if (process.env.SMTP_USER && process.env.SMTP_PASS) {
            await transporter.sendMail({
                from: `"CivicAI Automated System" <${process.env.SMTP_USER}>`,
                to: authorityEmail,
                subject: `[CivicAI Alert] ${report.severity} Severity Issue: ${report.category} (${report.trackingId})`,
                text: emailBody,
                html: `
                    <h2>Official CivicAI Report #${report.trackingId}</h2>
                    <p><strong>Category:</strong> ${report.category}</p>
                    <p><strong>Severity:</strong> ${report.severity}</p>
                    <hr/>
                    <div>${emailBody.replace(/\n/g, '<br/>')}</div>
                    <hr/>
                    ${primaryImage ? `<p><strong>Evidence attached:</strong></p><img src="${primaryImage}" width="400" />` : ''}
                    <p><small>This email was automatically generated by the CivicAI Citizen Advocate Agent.</small></p>
                `,
            });
            console.log(`📧 [Agent 1] Complaint email sent to ${authorityEmail}`);
        } else {
            console.log(`⚠️ SMTP credentials missing. Mocking email send to ${authorityEmail}`);
            console.log(`\n--- MOCK EMAIL BEGIN ---\nSubject: [CivicAI Alert] ${report.severity} Severity Issue\n${emailBody}\n--- MOCK EMAIL END ---\n`);
        }

        // 2. Audit Log the Agent Action
        await prisma.agentAction.create({
            data: {
                reportId: report.id,
                agentType: 'citizen_advocate',
                actionType: 'complaint_sent',
                recipientEmail: authorityEmail,
                details: {
                    generatedEmail: emailBody,
                    mocked: !(process.env.SMTP_USER && process.env.SMTP_PASS)
                },
                status: 'COMPLETED'
            }
        });

    } catch (error) {
        console.error("Agent 1 execution failed:", error);
        
        await prisma.agentAction.create({
            data: {
                reportId: reportId,
                agentType: 'citizen_advocate',
                actionType: 'complaint_sent_failed',
                details: JSON.parse(JSON.stringify(error, Object.getOwnPropertyNames(error))),
                status: 'FAILED'
            }
        });
    }
};
